### ISSUE TITLE
Update Filter panel to include a section for datasets

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#13]
In the filter panel on the tagging screen add a control to be able to select datasets to view, this needs to be a multi select as one could select multiple datasets. 

The current filter panel will probably need to be modified to allow room for this. one option is to condense the tagged/untagged/all into one control. but up to you

the API is still being worked on but the idea would it would just be another field in the "filter" section
e.g.
```
{
	"query": "", 
	"filter": {
		"tagged": false, 
		"untagged": true, 
		"hasComment" : false,
		"datasets": [1,2,3]
	}
}
```
and the path for the API would just be `/nltools/private/v1/search/1` where 1 is the project id

if datasets filter is not present we will just return data from all of the transformed datasets in the project

**Comment by Travmatolog** [comment]
Done. Datasets filter panel height will adjust automatically.
