### ISSUE TITLE
Add Dataset column to tagging grid

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#14]
We need to add a dataset column to the tagging grid so the user can see what dataset the transcription is from. We will include the dataset information in the data returned. 

for this would the ui have a map of the datasets and we can just return the id and you can get the name from the map? or should we return the id and name?

e.g. would this work? 

```
"transcriptionList":
    [{ "autoTagString":"agent",
        "numTokens":1,
        "autoTagCount":1,
        "documentCount":6873,
        "transcriptionHash":"f6ef3aef47bff007f5bbcbfb4ed61741941133db",
        "textStringForTagging":"representative"
        "datasets":[1,2,3]
    }]
```

A transcription could be in multiple datasets so we might need to be able to show multiple names in one cell. 

one gotcha which we need to figure out is how do we show if a transcription is in multiple datasets and is tagged differently in different datasets.

**Comment by Travmatolog** [comment]
Done.
