### ISSUE TITLE
Update Tag APIs to send datasets in the data package

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#15]
to tag transcriptions we'll need to be able to support sending multiple datasets with the request

if no datasets are given will apply to all of the matching transcriptions in all transformed datasets in the project

e.g. for tag
path to api will just be `nltools/private/v1/content/7/tag`

```
{
    "intent": "reservation-make",
    "username": "jeff.karpala@247-inc.com",
    "transcriptionHashList": ["ddb0e8dd3c4bfc487bd5c8290fa84259b07606c8"]
    "datasets": [1,2,3]
}
```

e.g. for remove tag
path to api will just be `nltools/private/v1/content/7/tag/delete`

```
{
    "username": "jeff.karpala@247-inc.com",
    "transcriptionHashList": ["ddb0e8dd3c4bfc487bd5c8290fa84259b07606c8"]
    "datasets": [1,2,3]
}
```

e.g. for update tag
path to api will just be `nltools/private/v1/content/7/tag/update`

```
{
    "intent": "reservation-make",
    "username": "jeff.karpala@247-inc.com",
    "transcriptionHashList": ["ddb0e8dd3c4bfc487bd5c8290fa84259b07606c8"]
    "datasets": [1,2,3]
}
```

**Comment by Travmatolog** [comment]
Tag and Comemnt api calls updated.
