### ISSUE TITLE
Update stats API calls to allow for multiple datasets

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#16]
we need to update the Stats api to allow for multiple datasets  

right now it's a GET to `/nltools/private/v1/search/7/datasets/7/stats`

we could allow for multiple in the path so `/nltools/private/v1/search/7/datasets/7,8,9/stats`

or change it to allow for a body and do path of `/nltools/private/v1/search/7/stats` with a body of 
```
{
    "datasets" : [7,8,9]
}
```

what would your suggestion be?

**Comment by Travmatolog** [comment]
I think it would be best to change search request url to:
`/search/[projectId]/`

And stats request method to JSON POST and url to:
`/search/[projectId]/stats`

For "stats" request similar to "search" - use "filter" payload parameter.
And in both cases in "filter" add ability to filter by "dataset":
`
{
    "filter": {
        "dataset": [[id], [id], ...]
    }
}
`

If the "dataset" key is omitted in "filter" that would mean we're querying for all datasets.

**Comment by jkarpala** [comment]
That makes sense for stats, I'll use that. 

for tagging and searching I referenced API changes similar to the ones you mentioned here in #13 and #15. in those I just have a datasets field as part of the main call but would you request also having the filter `{ "filter": { "dataset": [[id], [id], ...] } }` ?

**Comment by Travmatolog** [comment]
Yes, i think it would be good to use "filter": {"datasets": [...]} approach in stats request as well, and be consistent with "search" request.

As for "/content/[projectId]/tag", "/content/[projectId]/delete", "/content/[projectId]/comment", we definitely want to remove "dataset" part of the url. If several datasets can have same "transcriptionHash" record than i also agree to proposed formats from #13, #14.

There are few question remains open:

1. Can an "transcriptionHashList" item belong to datasets [1, 2, 3] while other item would belong to datasets [2, 3, 4]? In that case we should send dataset ids tied to each item instead of the global parameter like in #15.

2. When we're changing a "Tag" or "Comment" of particular "transcriptionHashList" item, we should no matter what was dataset filter value used in search, send all datasets ids of that item to correctly update all values across all datasets? Doesn't this mean that we can just omit datasetId parameter here?

**Comment by jkarpala** [comment]
it would simplify our data a lot of we just on comment and tag did that action against all transcription hashes in the project. and maybe we should start this way? Just not sure what the use case for having different tags for transcription in different datasets would be. so maybe for now we make it so tagging a transcription does it for all of those hash's in the project.

**Comment by Travmatolog** [comment]
Well if we're grouping "transcriptionHashes" by dataset ids in search response, we then need to change tag/comment for all datasets at once, in other way, i think, we should display separate row per each dataset then and handle them separately. If i understand correctly.

**Comment by 247manish** [comment]
We are not realizing it but this can quickly become very complex. Also actions depend upon how are we displaying unique utterances on the tagging page. Have we discussed that yet.

Showing only important columns here and all utterances tagged and untagged:

Utterance | Datasets | Intent
---------  | ----------- | ---------
I want to make a payment | LA, SFO |
Need to talk to an agent | SFO, NYC | agent-request

Note above I am showing utterances and the associated datasets from where it is coming from. Also note I am showing the labels of the datasets that a user would keep to easily identify. This is same as the name of the dataset, so we can use the dataset name. Showing a dataset ID here would not mean anything to the user. Of course in the JS code, it should refer to the actual dataset ID and the transcription hash while making actions.

Now if you want to tag something, it would be best if we make them tag that utterance from all the datasets. If we make it flexible, we will need to make it flexible at multiple places. However there is one exception and that is intent inheritance. Here they can override an intent that is inherited, so an utterance from different datasets can have multiple intents but that is done differently.

Net-net, before starting to implement, lets understand the requirements and use-cases. We need to discuss this with PSG, we should have done that earlier but better late than never.

**Comment by Travmatolog** [comment]
Great. That is what i was thinking off. For now i'll take care of initial stuff like new page routing and initialization requests and layout for datasets filter in separate branch. This can be made before we finalize requirements.

**Comment by Travmatolog** [comment]
Api calls updated.
