### ISSUE TITLE
Merged dataset view API and URLs don't match filtering criteria

### ISSUE THREAD

**Issue by 247manish** [247aitools/nlworkbench-ui#18]
Running the latest code, instead of clicking on the "Tag Datasets" button, I right clicked on one of the datasets and then selected "Tag Dataset" which uses the older API but also the URL is older.

Now on the tag datasets view, we show the datasets filter with only that particular dataset selected, and that is reflected in the UI as well.

However, at this point, I can check all the datasets and click on "Apply Filter" button to show me contents of all the datasets but notice, the URL still points to a specific dataset. This is incorrect.

What I recommend is we completely deprecate/remove the older API, oder URL etc. Even if the user right clicks on a specific dataset row and clicks "Tag Dataset", essentially you are filtering by that dataset, so the URL should still be "/tag-datasets/{projectId}" and in the request body(**SearchRequestFilter**) we should send the dataset ID of the selected dataset. So, if on the tag datasets page, if someone adds more datasets to the filtering criteria, there is no confusion and we continue using the newer API, newer URL etc.

<img width="1162" alt="screen shot 2017-08-02 at 2 30 37 pm" src="https://user-images.githubusercontent.com/27947257/28896315-c730a0f8-7790-11e7-9af8-2d40966f923f.png">

**Comment by 247manish** [comment]
@Travmatolog - You should change the UI to call only the newer API passing in the right values. We can remove the APIs once we remove all the references to it.

**Comment by Travmatolog** [comment]
Changed url to be always /tag-datasets/[projectId] to avoid confusion with selected datasets filter.
In project cascade menu and project datasets grid user still be able to set initial dataset filter.
