### ISSUE TITLE
No tagged green pop-up status message for tagging strings on merged dataset tagging view

### ISSUE THREAD

**Issue by 247manish** [247aitools/nlworkbench-ui#19]
This is an issue only on the first page in all of ours pages we show via pagination. That is we do not show the green pop-up status message stating an intent is successfully added if someone tags one or more text strings.

**Comment by Travmatolog** [comment]
Can you confirm the issue is still present? I can not reproduce it.

**Comment by 247manish** [comment]
I tested this from the latest master and I can reproduce it
