### ISSUE TITLE
Tag Datasets: double intents in case "Auto-tag" Dataset

### ISSUE THREAD

**Issue by Travmatolog** [247aitools/nlworkbench-ui#20]
Maybe not a bug.
Please check.

I have a Dataset with some tags already in it.
I create another dataset with "Auto-tag Dataset" opion On.
After transformation when i open Tag Datasets page intent column shows two same tags.
Please take a look at screenshot.

**Comment by Travmatolog** [comment]
![screenshot_41](https://user-images.githubusercontent.com/7236619/29081006-0b2cc9d4-7c6a-11e7-9bfc-0bb6e47715ff.png)

**Comment by 247manish** [comment]
ah, this could be a bug for me. This might be related to auto-tagging.

**Comment by jkarpala** [comment]
@247manish could you check your auto tag stuff and see if it's there? if not I'll investigate.

**Comment by 247manish** [comment]
Fixed as part of https://247inc.atlassian.net/browse/NT-864 internal ticket.
