### ISSUE TITLE
Update datasets statuses request format.

### ISSUE THREAD

**Issue by Travmatolog** [247aitools/nlworkbench-ui#5]
"/nltools/private/v1/projects/datasets/transform/status" - this api was designed to receive multiple datasets transformation statuses at once.

Currently it takes datasets ids array as a parameter
`["35", "36", "38", "39", "40"]`
and return associated array per dataset id like so 
`{"38":{"jobId":"35","task":"categorize","status":"RUNNING","errorCode":"OK","id":"69","createdAt":1497969007275,"modifiedAt":1497969007733,"percentComplete":0,"recordsProcessed":0,"recordsImported":12391}
}`

Dataset can now have different transformation status per project.
So i suggest we change parameters json format to {projectId: [datasetId, ...], ...}
`{"21": ["31", "32", "33"], "22": ["32", "34", "35"]}`
And associate data returned with keys in the same way.

**Comment by jkarpala** [comment]
@Travmatolog would it make more sense to only send the project ids? and then return the statuses for all of the projects datasets?

**Comment by Travmatolog** [comment]
It would work, but in general we want to reduce load on the server and amount of time for client to process data received and re-render ui components.
Client will only request datasets statuses we know are being transformed or queued, the request will be send between the short intervals of time to track statuses and update ui.
UI in this case could be opened cascade menu for any project from sidebar or datasets grid in project details, so we may want to track different projects/datasets at once, and only collect data we know can change .

**Comment by jkarpala** [comment]
@Travmatolog ok, makes sense. I'm working on the API and should be ready this afternoon

**Comment by jkarpala** [comment]
ok I'm adding an api that is a POST to `/nltools/private/v1/projects/transform/status`

accepts a json body with key of project id, and value of list of dataset ids e.g.
 
```
{ 
	"1" : ["1"], 
	"6" : ["6"] 
}
```

and returns key of project id, and value of map with key of dataset ids and values of task events e.g..
```
{
    "1": {
        "1": {
            "jobId": "1",
            "task": "index",
            "status": "COMPLETED",
            "errorCode": "OK",
            "id": "2",
            "createdAt": 1495746199949,
            "modifiedAt": 1495746415190,
            "percentComplete": 0,
            "recordsProcessed": 60047,
            "recordsImported": 60047
        }
    },
    "6": {
        "6": {
            "jobId": "12",
            "task": "index",
            "status": "CANCELLED",
            "errorCode": "ELKFAILED",
            "message": "Logstash job canceled",
            "id": "24",
            "createdAt": 1496878579401,
            "modifiedAt": 1496878586007,
            "percentComplete": 0,
            "recordsProcessed": 99128,
            "recordsImported": 12391
        }
    }
}
```

**Comment by Travmatolog** [comment]
When i'm requesting
https://tagging.247-inc.com:8443/nltools/private/v1/projects/datasets/transform/status
with
`{81: ["36"]}`
there is an exception: 
```
Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@7d2dfecd; line: 1, column: 1]
```
Please take a look. You can check in master.
