### ISSUE TITLE
Add action item to remove dataset from Project

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#6]
We need to give the user the ability to remove a dataset from a project. this does not delete the dataset itself and if the dataset is in other projects those are all untouched, but it does remove the mapping to the project and all data associated with the project/dataset.

API is DELETE to `/nltools/private/v1/projects/[projectId]/datasets/[datasetId]`

acceptance criteria:
- in the list of actions one can take on a dataset add the item to remove the dataset from the project. 
- this has to come with a confirmation that explicitly asks that the user is sure and that this cannot be reversed. 
- after the dataset is removed, if the user is on the project s the project screen should be updated with the new list of datasets

**Comment by jkarpala** [comment]
API has not been added yet, but ui could get started.

**Comment by Travmatolog** [comment]
Please take a look in master branch.
