### ISSUE TITLE
Clean up JS dependancies

### ISSUE THREAD

**Issue by jkarpala** [247aitools/nlworkbench-ui#9]
Clean up the JS dependancies, remove any unused ones, and fix and depreciation issues 

running web pack gives 
`(node:92491) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.`

**Comment by Travmatolog** [comment]
Done. Please be sure to read email about this update.
